root = "."
test_data_dir = "testdata"
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main ./cmd/main.go"
  bin = "./tmp/main"
  full_bin = ""

  include_dir = ["cmd", "internal"]
  exclude_dir = ["assets", "tmp", "vendor", "testdata"]
  include_ext = ["go", "tpl", "tmpl", "html", "toml"]

  delay = 1000
  stop_on_error = true
  log = "air.log"

[log]
  time = true

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"
